name: Building recovery

on:
  workflow_dispatch:

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
  DEVICE: a26x
  DT_LINK: https://github.com/Rerence1016/twrp-device-samsung-a26x/
  DT_PATH: device/samsung/a26x
  TARGET: recoveryimage
  FULL_PATH: /home/runner/work/twrp-device-samsung-a26x/twrp-device-samsung-a26x/work/out/target/product/a26x
  OUTPUT: recovery.tar

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
       - name: Checkout
         uses: actions/checkout@master


       - name: Free Disk Space (Ubuntu)
         uses: jlumbroso/free-disk-space@v1.3.1
         

       - name: Additional Storage Clearing
         run: |
            
            sudo rm -rf /opt/hostedtoolcache
            npm cache clean --force
            sudo apt-get remove --purge -y landscape-common snapd

            sudo apt-get autoremove -y         
            
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /etc/mysql
            sudo rm -rf /etc/php
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /usr/local/lib/android
            sudo rm -rf /opt/ghc
            sudo rm -rf /opt/hostedtoolcache/CodeQL
            sudo rm -rf /opt/az
            sudo rm -rf /opt/ghc 
            sudo rm -rf "/usr/local/share/boost" 
            sudo rm -rf "$AGENT_TOOLSDIRECTORY"
            
       - name: Initializing environment
         run: |
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            git config --global user.name ""
            git config --global user.email ""


       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1
             repo sync -c -j4 --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune --current-branch
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             sudo chmod a+rx $DT_PATH/mkbootimg
             
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh &&lunch twrp_$DEVICE-eng &&export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET

       - name: DEBUG - Check if recovery.img and recovery.tar exist
         run: |
              echo "Current directory is: $(pwd)"
              echo "Switching to: $FULL_PATH"
              cd /home/runner/work/twrp-device-samsung-a26x/twrp-device-samsung-a26x/work/
              echo "Checking for recovery files..."
              ls -alh out/target/product/a26x/
              if [ ! -f out/target/product/a26x/recovery.img ]; then
                echo "recovery.img not found!"
                exit 1
              else echo "recovery.img found!"
              fi
              if [ ! -f out/target/product/a26x/recovery.tar ]; then
                echo "recovery.tar not found!"
                exit 1
              else echo "recovery.tar found!"
              fi

       - name: Upload recovery.img
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: twrp-recovery-img
           path: $FULL_PATH/recovery.img

       - name: Upload recovery.tar
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: twrp-recovery-tar
           path: $FULL_PATH/recovery.tar
